- name: Pull kubernetes dashboard image
  docker_image:
    name: "{{ kube_dashboard_registry }}/kubernetes-dashboard-amd64"
    tag: v{{ kube_dashboard_version }}
- name: Deploy kubernetes dashboard
  include_tasks: k8s.yml
